import { GO_CONCEPTS } from '../concepts/concepts';
import { pos } from './buildState';
import type { TutorialCourse, TutorialLesson } from './types';

const CENTER_PLAYS: ReturnType<typeof pos>[] = [
  pos(3, 3),
  pos(3, 4),
  pos(3, 5),
  pos(4, 3),
  pos(4, 4),
  pos(4, 5),
  pos(5, 3),
  pos(5, 4),
  pos(5, 5),
];

export const TUTORIAL_LESSONS: TutorialLesson[] = [
  {
    id: 'place-first-stone',
    order: 1,
    title: 'Place Your First Stone',
    summary: 'Learn where stones go and who moves first.',
    steps: [
      {
        id: 'intro',
        kind: 'info',
        title: 'Stones go on the intersections',
        body: 'Go is played on the lines, not in the squares. Each empty intersection is a possible move.',
      },
      {
        id: 'first-play',
        kind: 'play',
        title: 'Place your first stone',
        body: 'Black plays first. Tap any highlighted empty intersection in the center to place a stone.',
        stones: [],
        currentPlayer: 'black',
        highlights: CENTER_PLAYS,
        validation: { kind: 'anyOf', positions: CENTER_PLAYS },
        correctFeedback: 'Well done! You placed your first stone.',
        wrongFeedback: 'That move is not allowed.',
        legalButWrongFeedback: 'That point is outside the highlighted area. Try one of the center intersections.',
        hints: [
          { message: 'Choose any highlighted empty intersection.', highlights: CENTER_PLAYS },
          { message: 'Tap one of the glowing center points.', highlights: CENTER_PLAYS },
        ],
      },
      {
        id: 'alternation',
        kind: 'info',
        title: 'Players alternate',
        body: 'After Black plays, White plays, then Black again. You always take turns — never play twice in a row.',
      },
    ],
  },
  {
    id: 'liberties',
    order: 2,
    title: 'Liberties',
    summary: 'Empty points next to a stone keep it alive.',
    steps: [
      {
        id: 'explain',
        kind: 'info',
        title: 'What is a liberty?',
        body: 'A liberty is an empty intersection directly up, down, left, or right of a stone. Diagonal points do not count.',
        stones: [{ row: 4, col: 4, color: 'black' }],
        highlights: [pos(3, 4), pos(5, 4), pos(4, 3), pos(4, 5)],
      },
      {
        id: 'extend',
        kind: 'play',
        title: 'Add a liberty',
        body: 'This black stone has only one liberty left. Play on that liberty to give your group more breathing room.',
        stones: [
          { row: 4, col: 4, color: 'black' },
          { row: 3, col: 4, color: 'white' },
          { row: 5, col: 4, color: 'white' },
          { row: 4, col: 3, color: 'white' },
        ],
        currentPlayer: 'black',
        highlights: [pos(4, 5)],
        validation: { kind: 'exact', position: pos(4, 5) },
        correctFeedback: 'Nice! Your stone now has more liberties.',
        wrongFeedback: 'That move is not allowed.',
        legalButWrongFeedback: 'That move does not use the last liberty. Look for the empty point beside the black stone.',
        hints: [
          { message: 'Count the empty points touching the black stone.', highlights: [pos(4, 5)] },
          { message: 'There is one liberty remaining.', highlights: [pos(4, 5)] },
          { message: 'Play on the highlighted liberty.', highlights: [pos(4, 5)] },
        ],
      },
    ],
  },
  {
    id: 'groups',
    order: 3,
    title: 'Groups',
    summary: 'Connected stones share liberties.',
    steps: [
      {
        id: 'connected',
        kind: 'info',
        title: 'Connected stones form a group',
        body: 'Stones of the same color connected horizontally or vertically are one group and share the same liberties.',
        stones: [
          { row: 4, col: 3, color: 'black' },
          { row: 4, col: 4, color: 'black' },
        ],
        highlights: [pos(3, 3), pos(3, 4), pos(3, 5), pos(4, 2), pos(4, 5), pos(5, 3), pos(5, 4), pos(5, 5)],
      },
      {
        id: 'diagonal',
        kind: 'info',
        title: 'Diagonal stones are not connected',
        body: 'Stones touching only diagonally are separate groups. Each must keep its own liberties.',
        stones: [
          { row: 4, col: 3, color: 'black' },
          { row: 5, col: 4, color: 'black' },
        ],
      },
      {
        id: 'connect',
        kind: 'play',
        title: 'Connect the groups',
        body: 'These two black stones are separate. Connect them into one group.',
        stones: [
          { row: 4, col: 3, color: 'black' },
          { row: 4, col: 5, color: 'black' },
        ],
        currentPlayer: 'black',
        validation: {
          kind: 'connectsGroups',
          anchors: [pos(4, 3), pos(4, 5)],
        },
        correctFeedback: 'Connected! They now share liberties as one group.',
        wrongFeedback: 'That move is not allowed.',
        legalButWrongFeedback: 'That move does not connect the two black stones. Play between them.',
        hints: [
          { message: 'Look for the empty point between the two black stones.' },
          { message: 'Play on the intersection that touches both stones.', highlights: [pos(4, 4)] },
          { message: 'Connect at the center point.', highlights: [pos(4, 4)] },
        ],
      },
    ],
  },
  {
    id: 'capture',
    order: 4,
    title: 'Capture',
    summary: 'Remove stones by filling their last liberty.',
    conceptId: 'capture',
    steps: [
      {
        id: 'explain',
        kind: 'info',
        title: 'Capturing stones',
        body: GO_CONCEPTS.capture.shortDefinition,
        conceptId: 'capture',
        learnMoreConcept: 'capture',
      },
      {
        id: 'capture-play',
        kind: 'play',
        title: 'Capture the white stone',
        body: 'White has one liberty left. Play the move that captures the white stone.',
        stones: [
          { row: 4, col: 4, color: 'white' },
          { row: 3, col: 4, color: 'black' },
          { row: 5, col: 4, color: 'black' },
          { row: 4, col: 3, color: 'black' },
        ],
        currentPlayer: 'black',
        highlights: [pos(4, 5)],
        validation: { kind: 'capture', color: 'white', minStones: 1 },
        correctFeedback: 'Captured! Filling the final liberty removes the group.',
        wrongFeedback: 'That move is not allowed.',
        legalButWrongFeedback: "That move is legal, but it doesn't capture the group. Find White's last liberty.",
        hints: [
          { message: "Count White's liberties." },
          { message: 'White has one liberty remaining.', highlights: [pos(4, 5)] },
          { message: 'Fill the final liberty to capture.', highlights: [pos(4, 5)] },
        ],
        conceptId: 'capture',
        learnMoreConcept: 'capture',
      },
    ],
  },
  {
    id: 'atari',
    order: 5,
    title: 'Atari',
    summary: 'One liberty left means a group is in danger.',
    conceptId: 'atari',
    steps: [
      {
        id: 'explain',
        kind: 'info',
        title: 'What is Atari?',
        body: GO_CONCEPTS.atari.shortDefinition,
        conceptId: 'atari',
        learnMoreConcept: 'atari',
      },
      {
        id: 'atari-play',
        kind: 'play',
        title: 'Put White in Atari',
        body: 'White has two liberties. Play so that White has only one liberty left.',
        stones: [
          { row: 4, col: 4, color: 'white' },
          { row: 3, col: 4, color: 'black' },
          { row: 5, col: 4, color: 'black' },
        ],
        currentPlayer: 'black',
        validation: { kind: 'atari', targetColor: 'white', anchor: pos(4, 4) },
        correctFeedback: 'Atari! White now has only one liberty and can be captured next.',
        wrongFeedback: 'That move is not allowed.',
        legalButWrongFeedback: 'That move is legal, but White still has more than one liberty. Reduce White to a single liberty.',
        hints: [
          { message: 'Look at the empty points touching the white stone.' },
          { message: 'Play next to White to reduce its liberties.' },
          { message: 'Try playing on the left liberty.', highlights: [pos(4, 3)] },
        ],
        conceptId: 'atari',
        learnMoreConcept: 'atari',
      },
    ],
  },
  {
    id: 'save-group',
    order: 6,
    title: 'Save a Group',
    summary: 'Escape Atari by adding liberties.',
    steps: [
      {
        id: 'explain',
        kind: 'info',
        title: 'Defending in Atari',
        body: 'When your group has only one liberty, you must add liberties or connect to safety on the next move.',
      },
      {
        id: 'escape',
        kind: 'play',
        title: 'Save your group',
        body: 'Your black stone is in Atari. Find a move that gives it more than one liberty.',
        stones: [
          { row: 4, col: 4, color: 'black' },
          { row: 3, col: 4, color: 'white' },
          { row: 5, col: 4, color: 'white' },
          { row: 4, col: 3, color: 'white' },
        ],
        currentPlayer: 'black',
        validation: { kind: 'groupLibertiesAtLeast', anchor: pos(4, 4), min: 2 },
        correctFeedback: 'Saved! Your group now has more liberties and is no longer in immediate danger.',
        wrongFeedback: 'That move is not allowed.',
        legalButWrongFeedback: 'That move is legal, but your group still has only one liberty. Add breathing room.',
        hints: [
          { message: 'Your group has one liberty. Where can you extend?' },
          { message: 'Play on the remaining liberty to escape.', highlights: [pos(4, 5)] },
          { message: 'Extend at the open point.', highlights: [pos(4, 5)] },
        ],
      },
    ],
  },
  {
    id: 'connect',
    order: 7,
    title: 'Connect',
    summary: 'Join friendly stones to share liberties.',
    conceptId: 'connect',
    steps: [
      {
        id: 'explain',
        kind: 'info',
        title: 'Why connect?',
        body: GO_CONCEPTS.connect.shortDefinition,
        conceptId: 'connect',
        learnMoreConcept: 'connect',
      },
      {
        id: 'connect-play',
        kind: 'play',
        title: 'Connect your stones',
        body: 'Connect these two black stones so they share liberties.',
        stones: [
          { row: 4, col: 3, color: 'black' },
          { row: 4, col: 5, color: 'black' },
          { row: 3, col: 4, color: 'white' },
        ],
        currentPlayer: 'black',
        validation: {
          kind: 'connectsGroups',
          anchors: [pos(4, 3), pos(4, 5)],
        },
        correctFeedback: 'Connected! Shared liberties make the group harder to capture.',
        wrongFeedback: 'That move is not allowed.',
        legalButWrongFeedback: 'That move is legal, but it does not connect the two black stones.',
        hints: [
          { message: 'Look for the empty point between your stones.' },
          { message: 'Play between the two black stones.', highlights: [pos(4, 4)] },
          { message: 'Connect at the center.', highlights: [pos(4, 4)] },
        ],
        conceptId: 'connect',
        learnMoreConcept: 'connect',
      },
    ],
  },
  {
    id: 'ko',
    order: 8,
    title: 'Ko',
    summary: 'Immediate recapture is forbidden.',
    conceptId: 'ko',
    steps: [
      {
        id: 'explain',
        kind: 'info',
        title: 'The Ko rule',
        body: GO_CONCEPTS.ko.shortDefinition,
        conceptId: 'ko',
        learnMoreConcept: 'ko',
      },
      {
        id: 'capture',
        kind: 'play',
        title: 'Capture the white stone',
        body: 'Capture the single white stone at the marked point.',
        stones: [
          { row: 7, col: 7, color: 'white' },
          { row: 8, col: 6, color: 'white' },
          { row: 8, col: 8, color: 'white' },
          { row: 6, col: 7, color: 'black' },
          { row: 7, col: 6, color: 'black' },
          { row: 7, col: 8, color: 'black' },
        ],
        currentPlayer: 'black',
        validation: { kind: 'capture', color: 'white', minStones: 1 },
        correctFeedback: 'Captured! Now try to take the stone back immediately on the next step.',
        wrongFeedback: 'That move is not allowed.',
        legalButWrongFeedback: 'Capture the isolated white stone.',
        hints: [
          { message: 'Find the white stone with only one liberty.' },
          { message: 'Play at the capture point.', highlights: [pos(8, 7)] },
        ],
        conceptId: 'ko',
        learnMoreConcept: 'ko',
      },
      {
        id: 'ko-illegal',
        kind: 'play',
        title: 'Try to recapture',
        body: 'Try to recapture immediately at the same point. The Ko rule should prevent it.',
        stones: [],
        presetState: 'ko-recapture-demo',
        currentPlayer: 'white',
        expectIllegal: true,
        illegalReason: 'ko',
        illegalSuccessFeedback:
          'Right — that recapture is forbidden by Ko. You must play elsewhere before recapturing.',
        validation: { kind: 'exact', position: pos(7, 7) },
        correctFeedback: '',
        wrongFeedback: 'Try playing where the captured stone was.',
        legalButWrongFeedback: 'Try the immediate recapture at the marked point.',
        hints: [
          { message: 'Try playing where the captured stone was.' },
          { message: 'Attempt the immediate recapture.', highlights: [pos(7, 7)] },
        ],
        conceptId: 'ko',
        learnMoreConcept: 'ko',
      },
      {
        id: 'ko-summary',
        kind: 'info',
        title: 'Ko prevents repetition',
        body: 'Immediate recapture would repeat the board position, so it is forbidden. You must play elsewhere first.',
        conceptId: 'ko',
        learnMoreConcept: 'ko',
      },
    ],
  },
  {
    id: 'territory',
    order: 9,
    title: 'Territory',
    summary: 'Surrounded empty points become territory.',
    steps: [
      {
        id: 'explain',
        kind: 'info',
        title: 'What is territory?',
        body: 'Empty intersections surrounded by your stones can become your territory at the end of the game.',
        stones: [
          { row: 2, col: 2, color: 'black' },
          { row: 2, col: 3, color: 'black' },
          { row: 2, col: 4, color: 'black' },
          { row: 3, col: 2, color: 'black' },
          { row: 4, col: 2, color: 'black' },
        ],
        showTerritory: true,
      },
      {
        id: 'summary',
        kind: 'info',
        title: 'Territory is not final until the end',
        body: 'During the game, surrounded areas may still be invaded. At the end, alive groups and surrounded empty points count toward your score.',
      },
    ],
  },
  {
    id: 'passing-scoring',
    order: 10,
    title: 'Passing & Scoring',
    summary: 'Pass to end the game and count the score.',
    steps: [
      {
        id: 'explain-pass',
        kind: 'info',
        title: 'Passing',
        body: 'When you have no useful moves left, you can pass. If both players pass in a row, the game enters scoring.',
      },
      {
        id: 'pass',
        kind: 'pass',
        title: 'Pass your turn',
        body: 'Both sides have finished this area. Press Pass to skip your turn.',
        stones: [
          { row: 3, col: 3, color: 'black' },
          { row: 3, col: 5, color: 'black' },
          { row: 5, col: 3, color: 'black' },
          { row: 5, col: 5, color: 'black' },
          { row: 3, col: 4, color: 'white' },
          { row: 4, col: 3, color: 'white' },
          { row: 4, col: 5, color: 'white' },
          { row: 5, col: 4, color: 'white' },
        ],
        currentPlayer: 'black',
        correctFeedback: 'You passed. When both players pass, scoring begins.',
        wrongFeedback: 'Try passing instead of playing a stone.',
        autoOpponentPass: true,
        hints: [{ message: 'Use the Pass button below the board.' }],
      },
      {
        id: 'scoring-info',
        kind: 'info',
        title: 'Chinese area scoring',
        body: "Let's Play Go uses Chinese area scoring: your score is stones on the board plus surrounded empty territory. Captured prisoners are not added. White also receives komi.",
      },
    ],
  },
  {
    id: 'first-9x9',
    order: 11,
    title: 'Play Your First 9×9 Game',
    summary: 'Practice on a full board with a simple local opponent.',
    steps: [
      {
        id: 'intro',
        kind: 'info',
        title: 'Your first full game',
        body: 'Play a short 9×9 practice game against a simple local opponent. Tips will appear when helpful. Pass when you are finished, then pass again to enter scoring.',
      },
      {
        id: 'play',
        kind: 'free-play',
        title: 'Play your first 9×9 game',
        body: 'Take your time. Corners are easier to surround than the center. Look for Atari and connections as you play.',
        size: 9,
        humanColor: 'black',
        targetMoves: 12,
        tips: [
          'Corners are easier to surround than the center.',
          'Keep your groups connected when possible.',
          'If a group has one liberty, it is in Atari.',
          'You can pass when you are finished.',
        ],
      },
    ],
  },
];

export const BEGINNER_TUTORIAL_COURSE: TutorialCourse = {
  id: 'beginner',
  title: 'Beginner Tutorial',
  description: 'Learn Go by playing through short, guided lessons.',
  lessons: TUTORIAL_LESSONS,
};

export function getTutorialLesson(lessonId: string): TutorialLesson | undefined {
  return TUTORIAL_LESSONS.find((lesson) => lesson.id === lessonId);
}

export function getNextLessonId(lessonId: string): string | null {
  const index = TUTORIAL_LESSONS.findIndex((lesson) => lesson.id === lessonId);
  if (index < 0 || index >= TUTORIAL_LESSONS.length - 1) {
    return null;
  }
  return TUTORIAL_LESSONS[index + 1]?.id ?? null;
}
